name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: TatsuXV
          outputs: |
            github-contribution-grid-snake.svg

      - name: Create simple index.html
        run: |
          echo '<html><body><img src="github-contribution-grid-snake.svg" /></body></html>' > index.html

      - name: Push to GitHub Pages branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
